/**
 * @file http_proxy.h
 * @brief Bidirectional relay between the TLS frontend and an upstream backend
 *
 * This module handles:
 *   1. Connecting to an upstream backend (plain TCP) with a timeout.
 *   2. Relaying data between the SSL* frontend and the backend fd using
 *      poll(), with idle/header timeouts, half-close support and graceful
 *      drain on shutdown.
 *   3. In HTTP mode, rewriting every request head (see http_rewriter.h) so
 *      the backend receives authoritative X-Forwarded-* and X-PQ-* headers.
 */

#ifndef PQ_HTTP_PROXY_H
#define PQ_HTTP_PROXY_H

#include <openssl/ssl.h>
#include <stdatomic.h>
#include <stddef.h>
#include <stdint.h>

typedef struct {
    size_t        bytes_from_client;   /* client -> backend */
    size_t        bytes_from_backend;  /* backend -> client */
    int           error;               /* 0 = clean close, <0 = error */
    int           http_status;         /* 400/408/431 if the proxy rejected a request */
    unsigned long requests;            /* request heads forwarded (HTTP mode) */
} pq_proxy_result_t;

/**
 * Connect to an upstream backend host:port with a timeout.
 *
 * @return socket fd >= 0 on success, -1 on error.
 */
int pq_proxy_connect_upstream(const char *host, uint16_t port, int timeout_ms);

/** Per-connection relay parameters */
typedef struct {
    const char *group_name;          /* e.g. "X25519MLKEM768"                  */
    const char *cipher_name;         /* e.g. "TLS_AES_256_GCM_SHA384"          */
    const char *client_addr;         /* peer IP, for X-Forwarded-For           */
    int         is_pq;               /* 1 if a post-quantum group was used     */
    int         rewrite_http;        /* 1 = HTTP mode, 0 = opaque TCP relay    */
    int         header_timeout_ms;   /* max time to receive one request head   */
    const atomic_int *running;       /* 0 => drain: close once the conn idles  */
    const atomic_int *force_stop;    /* 1 => close immediately                 */
} pq_proxy_info_t;

/**
 * Relay between a TLS frontend (ssl, on a blocking socket with SO_RCVTIMEO /
 * SO_SNDTIMEO set) and a backend socket until either side closes, the
 * connection is idle for idle_timeout_ms, or shutdown is requested.
 */
pq_proxy_result_t pq_proxy_relay(SSL *ssl, int backend_fd, int idle_timeout_ms,
                                 const pq_proxy_info_t *info);

/**
 * Send a minimal "HTTP/1.1 <status>" response with Connection: close.
 * Used for 400/408/431/502/503 answers generated by the proxy itself.
 */
void pq_proxy_send_status(SSL *ssl, int status, int timeout_ms);

#endif /* PQ_HTTP_PROXY_H */
