#!/bin/bash
# =========================================================================
# embed_assets.sh — Convert src/mgmt/static/** into static_assets.c
# Produces xxd-style byte arrays that are compiled into the binary.
# =========================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
STATIC_DIR="$PROJECT_DIR/src/mgmt/static"
OUTPUT_C="$PROJECT_DIR/src/mgmt/static_assets.c"

if [ ! -d "$STATIC_DIR" ]; then
    echo "Error: $STATIC_DIR not found"
    exit 1
fi

echo "Embedding static assets from: $STATIC_DIR"

# Start C file
cat > "$OUTPUT_C" << 'HEADER'
/**
 * @file static_assets.c
 * @brief Embedded frontend assets — AUTO-GENERATED by tools/embed_assets.sh
 *
 * DO NOT EDIT — regenerate with: bash tools/embed_assets.sh
 */

#include "static_assets.h"
#include <string.h>

HEADER

# Collect all files
ASSET_COUNT=0
ASSET_NAMES=""

# Find all files in static dir
while IFS= read -r -d '' file; do
    # Get relative path
    rel_path="${file#$STATIC_DIR/}"

    # Create C-safe variable name
    var_name="asset_$(echo "$rel_path" | sed 's/[^a-zA-Z0-9]/_/g')"

    # Generate xxd-style byte array
    echo "/* $rel_path */" >> "$OUTPUT_C"
    echo "static const unsigned char ${var_name}[] = {" >> "$OUTPUT_C"

    if command -v xxd >/dev/null 2>&1; then
        xxd -i < "$file" >> "$OUTPUT_C"
    else
        python3 -c "
import sys
data = open(sys.argv[1], 'rb').read()
for i, b in enumerate(data):
    if i > 0: sys.stdout.write(',')
    if i % 12 == 0: sys.stdout.write('\n  ')
    sys.stdout.write(' 0x%02x' % b)
sys.stdout.write('\n')
" "$file" >> "$OUTPUT_C"
    fi

    echo "};" >> "$OUTPUT_C"
    file_size=$(wc -c < "$file" | tr -d ' ')
    echo "static const size_t ${var_name}_len = ${file_size};" >> "$OUTPUT_C"
    echo "" >> "$OUTPUT_C"

    ASSET_NAMES="$ASSET_NAMES ${var_name}|${rel_path}|${file_size}"
    ASSET_COUNT=$((ASSET_COUNT + 1))

done < <(find "$STATIC_DIR" -type f -print0 | sort -z)

# Write asset table
echo "" >> "$OUTPUT_C"
echo "static const embedded_asset_t embedded_assets[] = {" >> "$OUTPUT_C"

for entry in $ASSET_NAMES; do
    var_name=$(echo "$entry" | cut -d'|' -f1)
    rel_path=$(echo "$entry" | cut -d'|' -f2)
    echo "    { \"${rel_path}\", ${var_name}, sizeof(${var_name}) }," >> "$OUTPUT_C"
done

echo "};" >> "$OUTPUT_C"
echo "" >> "$OUTPUT_C"
echo "static const int embedded_asset_count = ${ASSET_COUNT};" >> "$OUTPUT_C"

# Write lookup function
cat >> "$OUTPUT_C" << 'FOOTER'

const embedded_asset_t* find_embedded_asset(const char *path) {
    if (!path) return NULL;
    for (int i = 0; i < embedded_asset_count; i++) {
        if (strcmp(embedded_assets[i].path, path) == 0) {
            return &embedded_assets[i];
        }
    }
    return NULL;
}

int get_embedded_asset_count(void) {
    return embedded_asset_count;
}
FOOTER

echo "Generated $OUTPUT_C with $ASSET_COUNT assets"
