/**
 * @file config_writer.c
 * @brief INI config serializer with atomic write (tmp + rename)
 */

#include "config_writer.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static void write_section(FILE *fp, const char *name) {
    fprintf(fp, "\n[%s]\n", name);
}

static void write_kv(FILE *fp, const char *key, const char *val) {
    if (val && val[0]) fprintf(fp, "%s = %s\n", key, val);
}

static void write_kv_int(FILE *fp, const char *key, int val) {
    fprintf(fp, "%s = %d\n", key, val);
}

static void write_kv_bool(FILE *fp, const char *key, int val) {
    fprintf(fp, "%s = %s\n", key, val ? "true" : "false");
}

int pq_server_config_save(const pq_server_config_t *cfg, const char *path) {
    if (!cfg || !path || !path[0]) return -1;

    /* Write to temp file first */
    char tmp_path[2048];
    snprintf(tmp_path, sizeof(tmp_path), "%s.tmp.%d", path, getpid());

    FILE *fp = fopen(tmp_path, "w");
    if (!fp) return -1;

    fprintf(fp, "# PQ-TLS Server Configuration\n");
    fprintf(fp, "# Auto-generated by management dashboard\n");

    /* [listen] */
    write_section(fp, "listen");
    write_kv(fp, "address", cfg->bind_address);
    write_kv_int(fp, "port", cfg->listen_port);

    /* [tls] */
    write_section(fp, "tls");
    write_kv(fp, "cert", cfg->cert_file);
    write_kv(fp, "key", cfg->key_file);
    if (cfg->ca_file[0])
        write_kv(fp, "ca", cfg->ca_file);
    if (cfg->require_client_auth)
        write_kv_bool(fp, "client_auth", cfg->require_client_auth);
    write_kv(fp, "groups", cfg->tls_groups);
    fprintf(fp, "min_version = %s\n",
            cfg->tls_min_version == 0x0303 ? "1.2" : "1.3");
    if (cfg->session_cache_size > 0)
        write_kv_int(fp, "session_cache_size", cfg->session_cache_size);

    /* [upstream] */
    write_section(fp, "upstream");
    for (int i = 0; i < cfg->upstream_count; i++) {
        const pq_upstream_t *u = &cfg->upstreams[i];
        if (strncmp(u->host, "unix:", 5) == 0) {
            fprintf(fp, "backend = %s\n", u->host);
        } else {
            fprintf(fp, "backend = %s%s:%u",
                    u->use_tls ? "tls://" : "",
                    u->host, u->port);
            if (u->weight != 1)
                fprintf(fp, ";weight=%d", u->weight);
            fprintf(fp, "\n");
        }
    }
    if (cfg->upstream_timeout_ms != 30000)
        write_kv_int(fp, "timeout", cfg->upstream_timeout_ms);
    if (cfg->upstream_connect_timeout_ms != 5000)
        write_kv_int(fp, "connect_timeout", cfg->upstream_connect_timeout_ms);

    /* [server] / [workers] */
    write_section(fp, "server");
    write_kv_int(fp, "workers", cfg->worker_threads);
    write_kv_int(fp, "max_connections", cfg->max_connections);
    if (cfg->daemonize)
        write_kv_bool(fp, "daemonize", cfg->daemonize);
    if (cfg->pid_file[0])
        write_kv(fp, "pid_file", cfg->pid_file);

    /* [logging] */
    write_section(fp, "logging");
    if (cfg->log_file[0])
        write_kv(fp, "file", cfg->log_file);
    {
        const char *level_names[] = {"debug", "info", "warn", "error"};
        int lvl = cfg->log_level;
        if (lvl < 0) lvl = 0;
        if (lvl > 3) lvl = 3;
        write_kv(fp, "level", level_names[lvl]);
    }
    write_kv_bool(fp, "access_log", cfg->access_log);
    write_kv_bool(fp, "json", cfg->json_logging);

    /* [health] */
    write_section(fp, "health");
    write_kv_int(fp, "port", cfg->health_port);

    /* [rate_limit] */
    write_section(fp, "rate_limit");
    write_kv_int(fp, "per_ip", cfg->rate_limit_per_ip);
    if (cfg->rate_limit_burst > 0)
        write_kv_int(fp, "burst", cfg->rate_limit_burst);

    /* [acl] */
    if (cfg->acl_mode != PQ_ACL_MODE_DISABLED || cfg->acl_count > 0) {
        write_section(fp, "acl");
        const char *mode_str = "disabled";
        if (cfg->acl_mode == PQ_ACL_MODE_ALLOWLIST) mode_str = "allowlist";
        else if (cfg->acl_mode == PQ_ACL_MODE_BLOCKLIST) mode_str = "blocklist";
        write_kv(fp, "mode", mode_str);
        for (int i = 0; i < cfg->acl_count; i++) {
            write_kv(fp, "entry", cfg->acl_entries[i]);
        }
    }

    /* [mgmt] */
    write_section(fp, "mgmt");
    write_kv_bool(fp, "enabled", cfg->mgmt_enabled);
    if (cfg->mgmt_admin_user[0])
        write_kv(fp, "admin_user", cfg->mgmt_admin_user);
    if (cfg->mgmt_admin_pass_hash[0])
        write_kv(fp, "admin_pass_hash", cfg->mgmt_admin_pass_hash);
    if (cfg->cert_store_path[0])
        write_kv(fp, "cert_store", cfg->cert_store_path);

    /* Check for write errors before closing */
    int write_error = ferror(fp);
    fclose(fp);

    if (write_error) {
        unlink(tmp_path);
        return -1;
    }

    /* Atomic rename */
    if (rename(tmp_path, path) != 0) {
        unlink(tmp_path);
        return -1;
    }

    return 0;
}

int config_change_needs_restart(const char *section) {
    if (!section) return 1;

    /* These sections can be applied at runtime */
    if (strcmp(section, "rate_limit") == 0) return 0;
    if (strcmp(section, "acl") == 0) return 0;

    /* Everything else needs restart */
    return 1;
}
