/**
 * @file static_assets.h
 * @brief Embedded frontend assets — generated by tools/embed_assets.sh
 *
 * Each asset is stored as a byte array with its path and size.
 * The find_embedded_asset() function looks up assets by path.
 */

#ifndef PQ_STATIC_ASSETS_H
#define PQ_STATIC_ASSETS_H

#include <stddef.h>

typedef struct {
    const char          *path;
    const unsigned char *data;
    size_t               size;
} embedded_asset_t;

/**
 * Find an embedded asset by its path (e.g., "index.html", "css/main.css").
 * @return Pointer to asset or NULL if not found.
 */
const embedded_asset_t* find_embedded_asset(const char *path);

/**
 * Get the total number of embedded assets.
 */
int get_embedded_asset_count(void);

#endif /* PQ_STATIC_ASSETS_H */
